config/routes.rb
Rails.application.routes.draw do
  resources :opportunities

  root 'welcome#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state

  validates :state, presence: true
  validates :name, presence: true

  validates :name, uniqueness: { scope: :state,
    message: "Should not have the same name in a same state" }
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  belongs_to :city

  validates :title, :description, :how_to, :city, presence: true
end

app/models/state.rb
class State < ActiveRecord::Base

  validates :name, :acronym, presence: true
  validates :name, :acronym, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :set_opportunity, only: [:show, :edit, :update, :destroy]

  # GET /opportunities
  # GET /opportunities.json
  def index
    @opportunities = Opportunity.all
  end

  # GET /opportunities/1
  # GET /opportunities/1.json
  def show
  end

  # GET /opportunities/new
  def new
    @opportunity = Opportunity.new
  end

  # GET /opportunities/1/edit
  def edit
  end

  # POST /opportunities
  # POST /opportunities.json
  def create
    @opportunity = Opportunity.new(opportunity_params)

    respond_to do |format|
      if @opportunity.save
        format.html { redirect_to @opportunity, notice: 'Opportunity was successfully created.' }
        format.json { render :show, status: :created, location: @opportunity }
      else
        format.html { render :new }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opportunities/1
  # PATCH/PUT /opportunities/1.json
  def update
    respond_to do |format|
      if @opportunity.update(opportunity_params)
        format.html { redirect_to @opportunity, notice: 'Opportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @opportunity }
      else
        format.html { render :edit }
        format.json { render json: @opportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opportunities/1
  # DELETE /opportunities/1.json
  def destroy
    @opportunity.destroy
    respond_to do |format|
      format.html { redirect_to opportunities_url, notice: 'Opportunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opportunity
      @opportunity = Opportunity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opportunity_params
      params.require(:opportunity).permit(:title, :description, :how_to, :city_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Uma Nova Carreira", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li class="active"><a href="index.html">HOME</a></li>
        <li><a href="about.html">ABOUT</a></li>
        <li><a href="contact.html">CONTACT</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">PAGES <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="blog.html">BLOG</a></li>
            <li><a href="single-post.html">SINGLE POST</a></li>
            <li><a href="portfolio.html">PORTFOLIO</a></li>
            <li><a href="single-project.html">SINGLE PROJECT</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- link rel="shortcut icon" href="assets/ico/favicon.ico" -->
  <title>Uma Nova Carreira</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/opportunities/_form.html.erb
<%= simple_form_for(@opportunity) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :how_to %>
    <%= f.association :city %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/opportunities/edit.html.erb
<h1>Editing Opportunity</h1>

<%= render 'form' %>

<%= link_to 'Show', @opportunity %> |
<%= link_to 'Back', opportunities_path %>

app/views/opportunities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mtb">
  <div class="row">

    <div class="col-lg-8">
      <% @opportunities.each do |opportunity| %>
        <%= link_to opportunity do %>
          <h3 class="ctitle"><%= opportunity.title %></h3>
        <% end %>
        <p><csmall><%= opportunity.created_at %></csmall> | <csmall2><%= opportunity.city %></csmall2></p>
        <div class="hline"></div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'New Opportunity', new_opportunity_path %>

app/views/opportunities/new.html.erb
<div class="container mtb">
  <div class="row">
    <div class="col-lg-8">
      <h4>Ofereça uma nova oportunidade!</h4>
      <div class="hline"></div>
      <p>Lembre-se que você está oferecendo uma oportunidade de recomeço.
      As vagas não devem pedir experiência técnica ou idade específica.</p>

      <%= render 'form' %>
    </div>
  </div>
</div>

<%= link_to 'Back', opportunities_path %>

app/views/opportunities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @opportunity.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @opportunity.description %>
</p>

<p>
  <strong>How to:</strong>
  <%= @opportunity.how_to %>
</p>

<p>
  <strong>City:</strong>
  <%= @opportunity.city %>
</p>

<%= link_to 'Edit', edit_opportunity_path(@opportunity) %> |
<%= link_to 'Back', opportunities_path %>

app/views/welcome/_headerwrap.html.erb
<div id="headerwrap">
  <div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h1>Uma Nova Carreira</h1>
      <h3>Encontre um novo trabalho. Inicie uma nova vida.</h3>
      <h5>Mais da metade dos brasileiros não estão satisfeitos com seu emprego atual. Não é uma vergonha.</h5>
      <h5>Encontre aqui algo que goste e seja feliz.</h5>
    </div>
  </div>
  </div>
</div>

app/views/welcome/_service.html.erb
<div id="service">
  <div class="container">
    <div class="row centered">
      <div class="col-md-4">
        <i class="fa fa-heart-o"></i>
        <h4>Handsomely Crafted</h4>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
      </div>
      <div class="col-md-4">
        <i class="fa fa-flask"></i>
        <h4>Retina Ready</h4>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
      </div>
      <div class="col-md-4">
        <i class="fa fa-trophy"></i>
        <h4>Quality Theme</h4>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        <p><br/><a href="#" class="btn btn-theme">More Info</a></p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render "welcome/headerwrap" %>

<%= render "welcome/service" %>